name: sample_news
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  dio: 5.3.2
  retrofit: 4.0.1
  infinite_scroll_pagination: 4.0.0
  envied: 0.3.0+3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  get_it: 7.6.4
  injectable: 2.3.0
  flutter_bloc: 8.1.3
  lottie: 2.6.0
  go_router: 10.2.0
  cached_network_image: 3.2.3
  webview_flutter: 4.2.4
  url_launcher: 6.1.14
  intl: 0.18.1
  drag_and_drop_lists: 0.3.3
  mocktail: 1.0.0
  equatable: 2.0.5
  flutter_animate: 4.2.0+1
  animations: 2.0.8
  patrol_finders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 2.0.0
  retrofit_generator: 7.0.8
  build_runner: 2.4.6
  envied_generator: 0.3.0+3
  freezed: 2.4.1
  json_serializable: 6.7.1
  injectable_generator: 2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
  
  fonts:
    - family: Trirong
      fonts:
        - asset: assets/fonts/trirong_regular.ttf
          weight: 400
        - asset: assets/fonts/trirong_medium.ttf
          weight: 500
        - asset: assets/fonts/trirong_semibold.ttf
          weight: 600
        - asset: assets/fonts/trirong_bold.ttf
          weight: 700
    - family: WorkSans  
      fonts:
        - asset: assets/fonts/work_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/work_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans_semibold.ttf
          weight: 600
        - asset: assets/fonts/work_sans_bold.ttf
          weight: 700